'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import SpacePicker, { spaceLabel, type SpaceOption } from './SpacePicker';
import SpaceChooser from './SpaceChooser';
import { useApi } from '@/lib/client-api';
import { BellIcon, ComposeIcon, UserIcon } from './Icons';
import Avatar from './Avatar';
import { categories, categoryLabel, type Category } from '@/lib/categories';

type Viewer={id:string;display_name:string;username:string|null;avatar_url:string|null;show_avatar:boolean;has_custom_avatar?:boolean};
type Space=SpaceOption;
type Post={id:string;author_id:string;display_name:string;username:string|null;avatar_url:string|null;body:string;visibility:'public'|'private';space_id:string|null;space_name:string|null;category:Category|null;created_at:string;comment_count:string};
type Comment={id:string;author_id:string;display_name:string;avatar_url:string|null;body:string;created_at:string};
type Profile={user:Viewer;follow_status:string|null;counts:{followers:string;following:string}};
type Notice={id:string;kind:string;actor_id:string|null;actor_name:string|null;actor_avatar_url:string|null;post_id:string|null;comment_id:string|null;created_at:string};
type FollowRequest={id:string;follower_id:string;display_name:string;avatar_url:string|null};
type Report={id:string;target_type:'user'|'post'|'comment';target_id:string;reason:string;created_at:string};
const time=(value:string)=>new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
export default function App({initialPostId}:{initialPostId?:string}){
  const api=useApi(); const [viewer,setViewer]=useState<Viewer|null>(null); const [admin,setAdmin]=useState(false); const [spaces,setSpaces]=useState<Space[]>([]); const [spaceId,setSpaceId]=useState(''); const [categoryFilter,setCategoryFilter]=useState<Category|''>(''); const [tab,setTab]=useState<'feed'|'notifications'|'profile'|'admin'>('feed');
  const [posts,setPosts]=useState<Post[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [selectedPost,setSelectedPost]=useState<Post|null>(null);const [comments,setComments]=useState<Comment[]>([]);const [targetCommentId,setTargetCommentId]=useState<string|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [profilePosts,setProfilePosts]=useState<Post[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [requests,setRequests]=useState<FollowRequest[]>([]);const [unread,setUnread]=useState(0);const [reports,setReports]=useState<Report[]>([]);const [spaceName,setSpaceName]=useState('');const [spaceSlug,setSpaceSlug]=useState('');const [spaceParent,setSpaceParent]=useState('');const [spaceAliases,setSpaceAliases]=useState('');const [editingSpace,setEditingSpace]=useState('');
  const [comment,setComment]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
  const feedRequest=useRef(0);
  const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();}catch(e){setError(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}};
  const loadFeed=useCallback(async(selected:string,category:Category|'',more=false,next?:string|null)=>{const requestId=++feedRequest.current;const path=selected?`spaces/${selected}/posts`:'feed';const params=new URLSearchParams();if(category)params.set('category',category);if(more&&next)params.set('cursor',next);const data=await api<{items:Post[];next_cursor:string|null}>(`${path}${params.size?`?${params}`:''}`);if(requestId!==feedRequest.current)return;setPosts(current=>more?[...current,...data.items]:data.items);setCursor(data.next_cursor);},[api]);
  useEffect(()=>{window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand();run(async()=>{const [me,spaceData,notificationData]=await Promise.all([api<{viewer:Viewer;admin:boolean}>('me'),api<{items:Space[]}>('spaces'),api<{items:(Notice&{read_at:string|null})[]}>('me/notifications')]);setViewer(me.viewer);setAdmin(me.admin);setSpaces(spaceData.items);setUnread(notificationData.items.filter(item=>!item.read_at).length);await loadFeed('','');if(initialPostId){const commentId=new URLSearchParams(window.location.search).get('comment')||window.location.hash.match(/^#comment-([1-9]\d*)$/)?.[1];const target=commentId&&/^[1-9]\d*$/.test(commentId)?commentId:null;const detail=await api<{post:Post}>(`posts/${initialPostId}`);setSelectedPost(detail.post);const data=await api<{items:Comment[]}>(`posts/${initialPostId}/comments${target?`?target=${target}`:''}`);setComments(data.items);if(target&&data.items.some(item=>item.id===target))setTargetCommentId(target);}setReady(true);});},[api,initialPostId,loadFeed]);
  const openPostById=(postId:string,commentId:string|null=null)=>run(async()=>{const [data,found]=await Promise.all([api<{post:Post}>(`posts/${postId}`),api<{items:Comment[]}>(`posts/${postId}/comments${commentId?`?target=${commentId}`:''}`)]);const target=commentId&&found.items.some(c=>c.id===commentId)?commentId:null;setProfile(null);setSelectedPost(data.post);setComments(found.items);setTargetCommentId(target);history.pushState(null,'',`/posts/${postId}${target?`?comment=${target}`:''}`);if(commentId&&!target)setError('این کامنت دیگر در دسترس نیست؛ پست را باز کردیم.');});
  const openPost=(post:Post)=>openPostById(post.id);
  useEffect(()=>{if(!ready||!targetCommentId||!selectedPost)return;const frame=requestAnimationFrame(()=>document.getElementById(`comment-${targetCommentId}`)?.scrollIntoView({behavior:'smooth',block:'center'}));return()=>cancelAnimationFrame(frame);},[ready,targetCommentId,selectedPost,comments]);
  const openProfile=(userId:string)=>run(async()=>{const [p,feed]=await Promise.all([api<Profile>(`users/${userId}`),api<{items:Post[]}>(`users/${userId}/posts`)]);setProfile(p);setProfilePosts(feed.items);setSelectedPost(null);setTargetCommentId(null);history.pushState(null,'','/');});
  const toggleAvatar=()=>run(async()=>{if(!viewer||!profile||profile.user.id!==viewer.id)return;await api('me',{method:'PATCH',body:JSON.stringify({show_avatar:!profile.user.show_avatar})});await refreshOwnAvatar();});
  const refreshOwnAvatar=async()=>{if(!viewer)return;const [updated,feed]=await Promise.all([api<Profile>(`users/${viewer.id}`),api<{items:Post[]}>(`users/${viewer.id}/posts`)]);setProfile(updated);setProfilePosts(feed.items);await loadFeed(spaceId,categoryFilter);};
  const uploadAvatar=(file:File)=>run(async()=>{if(file.size>4*1024*1024)throw new Error('حداکثر حجم عکس ۴ مگابایت است.');const data=new FormData();data.set('image',file);await api('me/avatar',{method:'POST',body:data});await refreshOwnAvatar();});
  const removeAvatar=()=>run(async()=>{await api('me/avatar',{method:'DELETE'});await refreshOwnAvatar();});
  const back=()=>{setSelectedPost(null);setTargetCommentId(null);setProfile(null);history.pushState(null,'','/');};
  const submitComment=()=>run(async()=>{if(!selectedPost)return;await api(`posts/${selectedPost.id}/comments`,{method:'POST',body:JSON.stringify({body:comment})});setComment('');const result=await api<{items:Comment[]}>(`posts/${selectedPost.id}/comments`);setComments(result.items);});
  const showNotifications=()=>run(async()=>{const [n,r]=await Promise.all([api<{items:(Notice&{read_at:string|null})[]}>('me/notifications'),api<{items:FollowRequest[]}>('follow-requests')]);setNotices(n.items);setRequests(r.items);setTab('notifications');back();await Promise.all(n.items.filter(item=>!item.read_at).map(item=>api(`me/notifications/${item.id}`,{method:'POST'})));setUnread(0);});
  const openNotice=(notice:Notice)=>{if(notice.kind==='comment'&&notice.post_id)openPostById(notice.post_id,notice.comment_id);else if(notice.actor_id)openProfile(notice.actor_id);};
  const showAdmin=()=>run(async()=>{const data=await api<{items:Report[]}>('admin/reports');setReports(data.items);setTab('admin');back();});
  const report=(type:'post'|'user'|'comment',targetId:string)=>{const reason=prompt('دلیل گزارش را بنویسید:');if(!reason)return;run(async()=>{await api('reports',{method:'POST',body:JSON.stringify({target_type:type,target_id:targetId,reason})});alert('گزارش ثبت شد.');});};
  const clearSpaceForm=()=>{setSpaceName('');setSpaceSlug('');setSpaceParent('');setSpaceAliases('');setEditingSpace('');};
  const startChildSpace=(parentId:string)=>{clearSpaceForm();setSpaceParent(parentId);};
  const saveSpace=()=>run(async()=>{
    const path=editingSpace?`admin/spaces/${editingSpace}`:'admin/spaces';
    const aliases=[...new Set(spaceAliases.split(/[,،\n]/).map(item=>item.trim()).filter(Boolean))];
    await api(path,{method:editingSpace?'PATCH':'POST',body:JSON.stringify({name:spaceName,slug_segment:spaceSlug,parent_id:spaceParent||null,aliases,...(!editingSpace&&spaces.length===0?{is_default:true}:{})})});
    const data=await api<{items:Space[]}>('spaces');setSpaces(data.items);clearSpaceForm();
  });
  const postCard=(post:Post)=><article className="card" key={post.id}><div className="cardhead"><div className="author-line"><Avatar name={post.display_name} url={post.avatar_url} small/><button className="name" onClick={()=>openProfile(post.author_id)}>{post.display_name}</button></div><span className="muted">{time(post.created_at)}</span></div><p className="postbody" onClick={()=>openPost(post)}>{post.body}</p><div className="cardfoot"><span>{post.space_id&&spaces.find(s=>s.id===post.space_id)?spaceLabel(spaces.find(s=>s.id===post.space_id)!,spaces):post.space_name||'عمومی'} · {post.visibility==='private'?'خصوصی':'عمومی'}</span>{post.author_id===viewer?.id?<select className="post-category-select" aria-label="دستهٔ پست" value={post.category||''} onChange={event=>run(async()=>{await api(`posts/${post.id}`,{method:'PATCH',body:JSON.stringify({category:event.target.value||null})});await loadFeed(spaceId,categoryFilter);if(selectedPost?.id===post.id){const result=await api<{post:Post}>(`posts/${post.id}`);setSelectedPost(result.post);}})}><option value="">بدون دسته</option>{categories.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select>:post.category&&<span className="post-category-tag">{categoryLabel(post.category)}</span>}<button onClick={()=>openPost(post)}>گفت‌وگو ({post.comment_count})</button>{post.author_id===viewer?.id?<><button onClick={()=>{const changed=prompt('متن تازهٔ پست:',post.body);if(changed===null)return;run(async()=>{await api(`posts/${post.id}`,{method:'PATCH',body:JSON.stringify({body:changed})});await loadFeed(spaceId,categoryFilter);if(selectedPost?.id===post.id){const result=await api<{post:Post}>(`posts/${post.id}`);setSelectedPost(result.post);}});}}>ویرایش</button><button onClick={()=>{if(confirm('این پست حذف شود؟'))run(async()=>{await api(`posts/${post.id}`,{method:'DELETE'});setSelectedPost(null);await loadFeed(spaceId,categoryFilter);});}}>حذف</button></>:<button onClick={()=>report('post',post.id)}>گزارش</button>}</div></article>;
  return <div className="shell"><header><div><h1>پایه<span className="dot">.</span></h1><p>آدم‌های نزدیک، حرف‌های تازه</p></div><span className="badge">نسخهٔ آزمایشی</span></header>{error&&<div className="error" role="alert">{error}</div>}{!ready&&!error&&<p className="loading">در حال بارگذاری...</p>}
  {ready&&<><nav className="tabs" aria-label="ناوبری اصلی"><button className={`home-tab ${tab==='feed'&&!profile&&!selectedPost?'active':''}`} onClick={()=>{setTab('feed');back();setSpaceId('');setCategoryFilter('');run(()=>loadFeed('',''));}}>خانه</button><div className="nav-icons"><button className={`icon-button ${tab==='notifications'?'active-icon':''}`} aria-label="اعلان‌ها" title="اعلان‌ها" onClick={showNotifications}><BellIcon/>{unread>0&&<span className="unread-badge">{unread>9?'9+':unread}</span>}</button><button className={`icon-button ${tab==='profile'?'active-icon':''}`} aria-label="پروفایل من" title="پروفایل من" onClick={()=>{setTab('profile');openProfile(viewer!.id);}}><UserIcon/></button></div></nav>
  {selectedPost?<main><button className="back" onClick={back}>→ بازگشت</button>{postCard(selectedPost)}<h2>گفت‌وگو</h2>{comments.map(c=><article className={`comment${targetCommentId===c.id?" comment-target":""}`} id={`comment-${c.id}`} key={c.id}><div className="cardhead"><div className="author-line"><Avatar name={c.display_name} url={c.avatar_url} small/><button className="name" onClick={()=>openProfile(c.author_id)}>{c.display_name}</button></div><span className="muted">{time(c.created_at)}</span></div><p>{c.body}</p><div className="cardfoot">{c.author_id===viewer?.id&&<button onClick={()=>run(async()=>{await api(`comments/${c.id}`,{method:'DELETE'});setComments(comments.filter(x=>x.id!==c.id));})}>حذف</button>}<button onClick={()=>report('comment',c.id)}>گزارش</button></div></article>)}<div className="composer"><textarea placeholder="نظرت را بنویس..." value={comment} onChange={e=>setComment(e.target.value)} maxLength={2000}/><button className="primary" disabled={busy||!comment.trim()} onClick={submitComment}>ثبت کامنت</button></div></main>:
  profile?<main><button className="back" onClick={back}>→ بازگشت</button><section className="profile"><Avatar name={profile.user.display_name} url={profile.user.avatar_url}/><h2>{profile.user.display_name}</h2>{profile.user.username&&<p className="muted">@{profile.user.username}</p>}<p>{profile.counts.followers} دنبال‌کننده · {profile.counts.following} دنبال‌شونده</p><div className="actions">{profile.user.id!==viewer?.id&&<>{!profile.follow_status?<button className="primary" onClick={()=>run(async()=>{await api(`users/${profile.user.id}/follow`,{method:'POST'});await openProfile(profile.user.id);})}>درخواست دنبال‌کردن</button>:<button onClick={()=>run(async()=>{await api(`users/${profile.user.id}/follow`,{method:'DELETE'});await openProfile(profile.user.id);})}>{profile.follow_status==='accepted'?'لغو دنبال‌کردن':'لغو درخواست'}</button>}{profile.user.username&&<a className="button" href={`https://t.me/${profile.user.username}`} onClick={e=>{if(window.Telegram?.WebApp?.openTelegramLink){e.preventDefault();window.Telegram.WebApp.openTelegramLink(`https://t.me/${profile.user.username}`);}}}>پیام در تلگرام</a>}<button onClick={()=>report('user',profile.user.id)}>گزارش</button></>}{profile.user.id===viewer?.id&&<><div className="avatar-preference"><label className="avatar-toggle"><input type="checkbox" checked={profile.user.show_avatar} disabled={busy} onChange={toggleAvatar}/>نمایش عکس من به دیگران در پایه</label><small className="muted">عکس تلگرام به‌صورت پیش‌فرض نمایش داده می‌شود. می‌توانی آن را با عکس دلخواه جایگزین کنی.</small><label className="button avatar-upload">{profile.user.has_custom_avatar?"تغییر عکس":"بارگذاری عکس دلخواه"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)uploadAvatar(file);e.target.value="";}}/></label>{profile.user.has_custom_avatar&&<button type="button" onClick={removeAvatar} disabled={busy}>حذف عکس دلخواه و بازگشت به تلگرام</button>}</div>{admin&&<button onClick={showAdmin}>مدیریت پایه</button>}<button className="danger" onClick={()=>{if(confirm('حساب و تمام محتوای شما حذف شود؟'))run(async()=>{await api('me',{method:'DELETE'});location.reload();});}}>حذف حساب</button></>}</div></section><h2>پست‌ها</h2>{profilePosts.map(postCard)}</main>:
  tab==='notifications'?<main><h2>اعلان‌ها</h2>{requests.map(r=><div className="card notice-card" key={r.id}><button className="notice-link" onClick={()=>openProfile(r.follower_id)}><Avatar name={r.display_name} url={r.avatar_url} small/><span><strong>{r.display_name}</strong> درخواست دنبال‌کردن داده است.</span></button><div className="actions"><button className="primary" onClick={()=>run(async()=>{await api(`follow-requests/${r.id}/accept`,{method:'POST'});await showNotifications();})}>پذیرش</button><button onClick={()=>run(async()=>{await api(`follow-requests/${r.id}/reject`,{method:'POST'});await showNotifications();})}>رد</button></div></div>)}{notices.map(n=><div className="card notice-card" key={n.id}><button className="notice-link" disabled={!n.actor_id&&!(n.kind==='comment'&&n.post_id)} onClick={()=>openNotice(n)}><Avatar name={n.actor_name||'پ'} url={n.actor_avatar_url} small/><span><strong>{n.actor_name||'یک کاربر'}</strong> {n.kind==='comment'?'برای پستت کامنت گذاشت':n.kind==='follow_accepted'?'درخواستت را پذیرفت':'درخواست دنبال‌کردن داده است'}<small className="muted">{time(n.created_at)}</small></span></button></div>)}{!requests.length&&!notices.length&&<p className="empty">هنوز اعلانی نداری.</p>}</main>:
  tab==='admin'?<main><h2>مدیریت Space</h2><div className="composer">{editingSpace&&<p className="muted">در حال ویرایش «{spaces.find(s=>s.id===editingSpace)?.name}» هستید. برای ساخت زیر‌فضای جدید، از فهرست پایین «ساخت زیر‌فضا» را بزنید.</p>}<input placeholder="نام فضا" value={spaceName} onChange={e=>setSpaceName(e.target.value)}/><label>فضای والد<SpacePicker spaces={spaces.filter(s=>!editingSpace||s.id!==editingSpace&&!s.slug.startsWith(`${spaces.find(x=>x.id===editingSpace)?.slug}/`))} value={spaceParent} onChange={setSpaceParent} emptyLabel="فضای اصلی (بدون والد)" placeholder="جست‌وجوی فضای والد"/></label><input placeholder="اسلاگ همین فضا؛ مثلا entry-1403" value={spaceSlug} onChange={e=>setSpaceSlug(e.target.value.toLowerCase())}/><small className="muted">اسلاگ کامل: {spaces.find(s=>s.id===spaceParent)?.slug?`${spaces.find(s=>s.id===spaceParent)?.slug}/`:''}{spaceSlug||'…'}</small><textarea placeholder="نام‌های جایگزین، با ویرگول جدا کنید؛ مثل ورودی ۱۴۰۳" value={spaceAliases} onChange={e=>setSpaceAliases(e.target.value)} /><div className="actions"><button className="primary" disabled={busy||!spaceName.trim()||!spaceSlug.trim()} onClick={saveSpace}>{editingSpace?'ذخیرهٔ تغییرات':'ایجاد فضا'}</button>{editingSpace&&<button onClick={clearSpaceForm}>انصراف از ویرایش</button>}</div></div><h2>فضاهای موجود</h2>{spaces.map(s=><div className="card" key={s.id}><strong>{spaceLabel(s,spaces)}</strong><small className="space-path">{s.slug}</small><div className="actions"><button onClick={()=>startChildSpace(s.id)}>ساخت زیر‌فضا</button><button onClick={()=>{setEditingSpace(s.id);setSpaceName(s.name);setSpaceSlug(s.slug_segment);setSpaceParent(s.parent_id||'');setSpaceAliases(s.aliases.join('، '));}}>ویرایش</button></div></div>)}<h2>گزارش‌های باز</h2>{reports.map(r=><div className="card" key={r.id}><p>{r.target_type} #{r.target_id}: {r.reason}</p><div className="actions"><button onClick={()=>run(async()=>{await api(`admin/${r.target_type==='user'?'users':r.target_type==='post'?'posts':'comments'}/${r.target_id}${r.target_type==='user'?'/disable':''}`,{method:r.target_type==='user'?'POST':'DELETE'});await api(`admin/reports/${r.id}`,{method:'PATCH'});await showAdmin();})}>{r.target_type==='user'?'غیرفعال‌کردن کاربر':'حذف محتوا'}</button><button onClick={()=>run(async()=>{await api(`admin/reports/${r.id}`,{method:'PATCH'});await showAdmin();})}>بستن گزارش</button></div></div>)}{!reports.length&&<p className="empty">گزارش بازی وجود ندارد.</p>}</main>:
  <main className="feed-main"><div className="feedtitle"><h2>فید</h2><SpaceChooser spaces={spaces} value={spaceId} onChange={id=>{setSpaceId(id);run(()=>loadFeed(id,categoryFilter));}} mode="feed"/></div><div className="category-filters" role="group" aria-label="فیلتر دستهٔ پست"><button type="button" aria-pressed={!categoryFilter} className={!categoryFilter?'active':''} onClick={()=>{setCategoryFilter('');run(()=>loadFeed(spaceId,''));}}>همه</button>{categories.map(item=><button type="button" key={item.id} aria-pressed={categoryFilter===item.id} className={categoryFilter===item.id?'active':''} onClick={()=>{setCategoryFilter(item.id);run(()=>loadFeed(spaceId,item.id));}}>{item.label}</button>)}</div>{posts.map(postCard)}{!posts.length&&<p className="empty">{categoryFilter?'در این دسته هنوز پستی نیست.':'اینجا هنوز پستی نیست. اولین گفت‌وگو را شروع کن.'}</p>}{cursor&&<button className="more" disabled={busy} onClick={()=>run(()=>loadFeed(spaceId,categoryFilter,true,cursor))}>پست‌های بیشتر</button>}</main>}
  {tab==='feed'&&!profile&&!selectedPost&&<a className="compose-fab" href={spaceId?`/compose?space=${encodeURIComponent(spaceId)}`:'/compose'} aria-label="نوشتن پست جدید" title="نوشتن پست جدید"><ComposeIcon/></a>}</>}</div>;
}
